---
multi_dof_joints:
  -
    name: world_joint
    type: Floating
    parent_frame_id: base_link
    child_frame_id: base_link
groups:
  -
    name: SchunkArm
    base_link: DH1
    tip_link: Gripper
default_collision_operations:
  -
    object1: base_link
    object2: DH1
    operation: disable  # Adjacent in collision
  -
    object1: DH1
    object2: ConnBase
    operation: disable  # Adjacent in collision
  -
    object1: DH1
    object2: DH2
    operation: disable  # Adjacent in collision
  -
    object1: DH2
    object2: DH3
    operation: disable  # Adjacent in collision
  -
    object1: DH3
    object2: ConnLong1
    operation: disable  # Adjacent in collision
  -
    object1: DH3
    object2: DH4
    operation: disable  # Adjacent in collision
  -
    object1: DH4
    object2: ConnLong2
    operation: disable  # Adjacent in collision
  -
    object1: DH4
    object2: DH5
    operation: disable  # Adjacent in collision
  -
    object1: DH5
    object2: DH6
    operation: disable  # Adjacent in collision
  -
    object1: DH6
    object2: Gripper
    operation: disable  # Adjacent in collision
  -
    object1: Gripper
    object2: GFneg
    operation: disable  # Adjacent in collision
  -
    object1: Gripper
    object2: GFpos
    operation: disable  # Adjacent in collision
  -
    object1: base_link
    object2: tail
    operation: disable  # Adjacent in collision
  -
    object1: ConnBase
    object2: ConnLong1
    operation: disable  # Never in collision
  -
    object1: ConnBase
    object2: DH2
    operation: disable  # Never in collision
  -
    object1: ConnBase
    object2: DH3
    operation: disable  # Never in collision
  -
    object1: ConnBase
    object2: DH4
    operation: disable  # Never in collision
  -
    object1: ConnBase
    object2: DH5
    operation: disable  # Never in collision
  -
    object1: ConnBase
    object2: DH6
    operation: disable  # Never in collision
  -
    object1: ConnBase
    object2: base_link
    operation: disable  # Never in collision
  -
    object1: ConnBase
    object2: tail
    operation: disable  # Never in collision
  -
    object1: ConnLong1
    object2: ConnLong2
    operation: disable  # Never in collision
  -
    object1: ConnLong1
    object2: DH2
    operation: disable  # Never in collision
  -
    object1: ConnLong1
    object2: DH4
    operation: disable  # Never in collision
  -
    object1: ConnLong1
    object2: DH5
    operation: disable  # Never in collision
  -
    object1: ConnLong1
    object2: DH6
    operation: disable  # Never in collision
  -
    object1: ConnLong1
    object2: GFneg
    operation: disable  # Never in collision
  -
    object1: ConnLong1
    object2: GFpos
    operation: disable  # Never in collision
  -
    object1: ConnLong1
    object2: tail
    operation: disable  # Never in collision
  -
    object1: ConnLong2
    object2: DH2
    operation: disable  # Never in collision
  -
    object1: ConnLong2
    object2: DH3
    operation: disable  # Never in collision
  -
    object1: ConnLong2
    object2: DH5
    operation: disable  # Never in collision
  -
    object1: ConnLong2
    object2: DH6
    operation: disable  # Never in collision
  -
    object1: ConnLong2
    object2: GFneg
    operation: disable  # Never in collision
  -
    object1: ConnLong2
    object2: GFpos
    operation: disable  # Never in collision
  -
    object1: ConnLong2
    object2: tail
    operation: disable  # Never in collision
  -
    object1: DH2
    object2: DH4
    operation: disable  # Never in collision
  -
    object1: DH2
    object2: DH5
    operation: disable  # Never in collision
  -
    object1: DH2
    object2: DH6
    operation: disable  # Never in collision
  -
    object1: DH2
    object2: base_link
    operation: disable  # Never in collision
  -
    object1: DH2
    object2: tail
    operation: disable  # Never in collision
  -
    object1: DH3
    object2: DH5
    operation: disable  # Never in collision
  -
    object1: DH3
    object2: DH6
    operation: disable  # Never in collision
  -
    object1: DH3
    object2: base_link
    operation: disable  # Never in collision
  -
    object1: DH3
    object2: tail
    operation: disable  # Never in collision
  -
    object1: DH4
    object2: DH6
    operation: disable  # Never in collision
  -
    object1: DH4
    object2: base_link
    operation: disable  # Never in collision
  -
    object1: DH4
    object2: tail
    operation: disable  # Never in collision
  -
    object1: DH5
    object2: GFneg
    operation: disable  # Never in collision
  -
    object1: DH5
    object2: GFpos
    operation: disable  # Never in collision
  -
    object1: DH5
    object2: Gripper
    operation: disable  # Never in collision
  -
    object1: DH5
    object2: base_link
    operation: disable  # Never in collision
  -
    object1: DH5
    object2: tail
    operation: disable  # Never in collision
  -
    object1: DH6
    object2: GFneg
    operation: disable  # Never in collision
  -
    object1: DH6
    object2: GFpos
    operation: disable  # Never in collision
  -
    object1: DH6
    object2: base_link
    operation: disable  # Never in collision
  -
    object1: DH6
    object2: tail
    operation: disable  # Never in collision
  -
    object1: GFneg
    object2: GFpos
    operation: disable  # Never in collision