multi_dof_joints:
  - name: world_joint
    type: Floating
    parent_frame_id: base_link
    child_frame_id: base_link
groups:
  - name: SchunkArm
    base_link: arm_base_link
    tip_link: gripper
default_collision_operations:
  - object1: base_link
    object2: arm_base_link
    operation: disable  # Adjacent in collision
  - object1: arm_base_link
    object2: arm_base_connector
    operation: disable  # Adjacent in collision
  - object1: arm_base_link
    object2: arm_link_1
    operation: disable  # Adjacent in collision
  - object1: arm_link_1
    object2: arm_link_2
    operation: disable  # Adjacent in collision
  - object1: arm_link_2
    object2: arm_link_2_connector
    operation: disable  # Adjacent in collision
  - object1: arm_link_2
    object2: arm_link_3
    operation: disable  # Adjacent in collision
  - object1: arm_link_3
    object2: arm_link_3_connector
    operation: disable  # Adjacent in collision
  - object1: arm_link_3
    object2: arm_link_4
    operation: disable  # Adjacent in collision
  - object1: arm_link_4
    object2: arm_link_5
    operation: disable  # Adjacent in collision
  - object1: arm_link_5
    object2: gripper
    operation: disable  # Adjacent in collision
  - object1: gripper
    object2: GFneg
    operation: disable  # Adjacent in collision
  - object1: GFneg
    object2: GFpos
    operation: disable  # Adjacent in collision
  - object1: gripper
    object2: camera_mount
    operation: disable  # Adjacent in collision
  - object1: camera_mount
    object2: kinect
    operation: disable  # Adjacent in collision
  - object1: base_link
    object2: tail
    operation: disable  # Adjacent in collision
  - object1: camera_mount
    object2: arm_link_3_connector
    operation: disable  # Never in collision
  - object1: camera_mount
    object2: arm_link_3
    operation: disable  # Never in collision
  - object1: camera_mount
    object2: arm_link_4
    operation: disable  # Never in collision
  - object1: camera_mount
    object2: arm_link_5
    operation: disable  # Never in collision
  - object1: camera_mount
    object2: GFneg
    operation: disable  # Never in collision
  - object1: camera_mount
    object2: GFpos
    operation: disable  # Never in collision
  - object1: arm_base_connector
    object2: arm_link_2_connector
    operation: disable  # Never in collision
  - object1: arm_base_connector
    object2: arm_link_1
    operation: disable  # Never in collision
  - object1: arm_base_connector
    object2: arm_link_2
    operation: disable  # Never in collision
  - object1: arm_base_connector
    object2: arm_link_3
    operation: disable  # Never in collision
  - object1: arm_base_connector
    object2: arm_link_4
    operation: disable  # Never in collision
  - object1: arm_base_connector
    object2: arm_link_5
    operation: disable  # Never in collision
  - object1: arm_base_connector
    object2: base_link
    operation: disable  # Never in collision
  - object1: arm_base_connector
    object2: tail
    operation: disable  # Never in collision
  - object1: arm_link_2_connector
    object2: arm_link_3_connector
    operation: disable  # Never in collision
  - object1: arm_link_2_connector
    object2: arm_link_1
    operation: disable  # Never in collision
  - object1: arm_link_2_connector
    object2: arm_link_3
    operation: disable  # Never in collision
  - object1: arm_link_2_connector
    object2: arm_link_4
    operation: disable  # Never in collision
  - object1: arm_link_2_connector
    object2: arm_link_5
    operation: disable  # Never in collision
  - object1: arm_link_2_connector
    object2: tail
    operation: disable  # Never in collision
  - object1: arm_link_3_connector
    object2: arm_link_2
    operation: disable  # Never in collision
  - object1: arm_link_3_connector
    object2: arm_link_4
    operation: disable  # Never in collision
  - object1: arm_link_3_connector
    object2: arm_link_5
    operation: disable  # Never in collision
  - object1: arm_link_3_connector
    object2: GFneg
    operation: disable  # Never in collision
  - object1: arm_link_3_connector
    object2: GFpos
    operation: disable  # Never in collision
  - object1: arm_link_3_connector
    object2: gripper
    operation: disable  # Never in collision
  - object1: arm_link_3_connector
    object2: tail
    operation: disable  # Never in collision
  - object1: arm_link_1
    object2: arm_link_3
    operation: disable  # Never in collision
  - object1: arm_link_1
    object2: arm_link_4
    operation: disable  # Never in collision
  - object1: arm_link_1
    object2: arm_link_5
    operation: disable  # Never in collision
  - object1: arm_link_1
    object2: base_link
    operation: disable  # Never in collision
  - object1: arm_link_1
    object2: tail
    operation: disable  # Never in collision
  - object1: arm_link_2
    object2: arm_link_4
    operation: disable  # Never in collision
  - object1: arm_link_2
    object2: arm_link_5
    operation: disable  # Never in collision
  - object1: arm_link_2
    object2: base_link
    operation: disable  # Never in collision
  - object1: arm_link_2
    object2: tail
    operation: disable  # Never in collision
  - object1: arm_link_3
    object2: arm_link_5
    operation: disable  # Never in collision
  - object1: arm_link_3
    object2: GFneg
    operation: disable  # Never in collision
  - object1: arm_link_3
    object2: GFpos
    operation: disable  # Never in collision
  - object1: arm_link_3
    object2: gripper
    operation: disable  # Never in collision
  - object1: arm_link_3
    object2: base_link
    operation: disable  # Never in collision
  - object1: arm_link_3
    object2: tail
    operation: disable  # Never in collision
  - object1: arm_link_4
    object2: GFneg
    operation: disable  # Never in collision
  - object1: arm_link_4
    object2: GFpos
    operation: disable  # Never in collision
  - object1: arm_link_4
    object2: gripper
    operation: disable  # Never in collision
  - object1: arm_link_4
    object2: kinect
    operation: disable  # Never in collision
  - object1: arm_link_4
    object2: base_link
    operation: disable  # Never in collision
  - object1: arm_link_4
    object2: tail
    operation: disable  # Never in collision
  - object1: arm_link_5
    object2: GFneg
    operation: disable  # Never in collision
  - object1: arm_link_5
    object2: GFpos
    operation: disable  # Never in collision
  - object1: arm_link_5
    object2: kinect
    operation: disable  # Never in collision
  - object1: arm_link_5
    object2: base_link
    operation: disable  # Never in collision
  - object1: arm_link_5
    object2: tail
    operation: disable  # Never in collision
  - object1: GFneg
    object2: kinect
    operation: disable  # Never in collision
  - object1: GFpos
    object2: gripper
    operation: disable  # Never in collision
  - object1: GFpos
    object2: kinect
    operation: disable  # Never in collision
  - object1: gripper
    object2: kinect
    operation: disable  # Never in collision
